/** @format */

"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { createContext, useState } from "react";
// import { UidContextProvider } from "../context/uidContext";

const inter = Inter({ subsets: ["latin"] });

export const UidContext = createContext();

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, setUser] = useState();

  return (
    <html lang="en">
      <body className={inter.className}>
        <UidContext.Provider
          value={{
            user,
            setUser,
          }}
        >
          {children}
        </UidContext.Provider>
      </body>
    </html>
  );
}
